[language-server.copilot]
command = "copilot"
args = ["--stdio"]

[[language]]
name = "ocaml"
formatter = { command = "ocamlformat", args = [
    "-",
    "--impl",
    "--enable-outside-detected-project", # Enable only if you want to format files outside of projects
] }

[language-server.clangd]
command = "clangd"
# args = "-std=c++20"
config = { "clangd.fallbackFlags" = [ "-std=c++20" ] }
args=["--compile-commands-dir=$HOME"]

[[language]]
name = "cpp"
language-servers = ["clangd", "copilot"]

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
language-servers = ["pyright", "ruff"]

[language-server.godot]
command = "nc" 
args = [ "127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = [ "godot" ]
